---
# tasks file for tbumke.pik3s

- name: Get facts
  ansible.builtin.include_tasks: get_facts.yml
  tags: [always]

- name: Include prerequisites
  ansible.builtin.include_tasks: prerequisites.yml
  tags: [always]

- name: Include LVM tasks
  ansible.builtin.include_tasks: lvm.yml
  tags: [always]

- name: Include installation tasks
  when: installed_k3s_version is undefined or installed_k3s_version is version(pik3s_version, '<')
  ansible.builtin.include_tasks: installation.yml
  tags: [always]
