---
# tasks file for tbumke.pik3s

- name: Get facts
  ansible.builtin.include_tasks: get_facts.yml
  tags: [always]

- name: Include prerequisites
  ansible.builtin.include_tasks: prerequisites.yml
  tags: [always]

- name: Include LVM tasks
  ansible.builtin.include_tasks: lvm.yml
  tags: [always]
