---
- name: Install iptables
  ansible.builtin.package:
    name: iptables
    state: present
  tags: [prereq]

- name: Ensure cgroups are enabled
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*) rootwait$'
    line: '\1 rootwait cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  tags: [prereq]
